blogApp/urls.py
from django.urls import path
from . import views

urlpatterns =[
    
    path('about',views.AboutTemplate.as_view(), name= 'about'),
    path('contact',views.ContactTemplate.as_view(), name= 'contact'),
    path('create',views.CreateTemplate.as_view(), name= 'create'),
    path('draft',views.DraftListView.as_view(), name='draft'),
    path('update/<int:pk>',views.UpdateRecs.as_view(),name='update'),
    path('delete/<int:pk>',views.DeletePost.as_view(),name='delete'),
    path('post_detail/<int:pk>',views.PostDetailView.as_view(),name='post_detail'),
    path("publish/<int:pk>",views.puplish_drafts_post,name="publish"),
    path('comment/<int:pk>',views.AddCommentView.as_view(),name='comment'),
    path('reply/<int:pk>',views.AddCommentView.as_view(),name='reply'),
    path('approve/comment/<int:pk>', views.ApproveComment.as_view(), name='c_approve'),
    path('like/<int:pk>',views.LikeView,name='like_post'),
    path('add/category',views.AddCategoryView.as_view(), name= 'addcats'),

    path('category/<str:cats>/',views.CategoryListView, name= 'category'),
    
]

myApp/urls.py
from django.urls import path
from django.contrib import admin
from . import views



urlpatterns = [
    path('',views.IndexTemplate.as_view(), name='index'),
    path('myblog/',views.BlogTemplate.as_view(), name= 'myblog'),
    path('single/',views.SIngleTemplate.as_view(), name= 'single'),
    path('login/',views.LoginTemplate.as_view(), name= 'login'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings
from myApp import views
from blogApp import views

urlpatterns = [
    # path('',views.PostList, name= 'blog'),
    path('',views.HomeListView.as_view(), name= 'blog'),
    path('blogApp/',include('blogApp.urls')),
    path('myApp/',include('myApp.urls')),
    path('admin_user/', include('django.contrib.auth.urls')),
    path('admin_user/',include('admin_user.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogApp/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField # comming back for this 
# from djrichtextfield.models import RichTextField     come back for this


# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=225)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('post_category', kwargs={'pk': self.pk})

    def get_absolute_url(self):
        return reverse("blog")



# import sys

# from PIL import Image
# from io import BytesIO
# from django.core.files.uploadedfile import InMemoryUploadedFile

class Post(models.Model):

    author         = models.ForeignKey(User,on_delete=models.CASCADE)
    # category       = models.ForeignKey(Category,related_name='categories', on_delete=models.CASCADE)
    category      = models.CharField(max_length=120)
    title          = models.CharField(max_length=100)
    text           = RichTextField(blank=True, null=True)
    featured_image = models.ImageField(upload_to='featured_images',blank=True)
    created_date   = models.DateTimeField(auto_now_add=True)
    published_date = models.DateTimeField(blank=True,null=True)
    likes          = models.ManyToManyField(User,related_name= "author")

    def total_likes(self):
        return self.likes.count()


    def count_like(self):
        qs = Post.objects.filter(likes='likes', author= False)
        if qs.exists():
            return qs[0].Post.count()

    def total_cats(self):
        return self.category.count() 



    def ordering(self):
        published_date = ['-publish_date',]
        created_date = ['-publish_date',]
        return self.created_date +" " + self.published_date

   

    def __str__(self):
        return self.title + " " + str(self.category)

    def post_count(self):
        p_count = Post.objects.count()
        return self.P_count

    

    def get_absolute_url(self):
        return reverse("post_detail", kwargs={"pk": self.pk})

    def published_post(self):
        self.published_date = timezone.now()
        self.save()
    # def approved_comment(self):
        #     return self.comments.filter(approved_comments = True)
    
    

class Comment(models.Model):
  
    post              = models.ForeignKey(Post, on_delete=models.CASCADE,related_name='comments' )
    name              = models.ForeignKey(User, on_delete=models.CASCADE)
    body              = models.TextField()
    created_date      = models.DateTimeField(auto_now_add=True)
    approved_comment  = models.BooleanField(default=False)
    parent            = models.ForeignKey("self", on_delete=models.SET_NULL, null="True",  blank="True")

    def ordering(self):
        created_date = ('-comment_date',)

    def approve(self):
        self.approved_comment = True
        self.save()

    def count_comment(self):
        qs = Comment.objects.filter(post='post', comments= False)
        if qs.exists():
            return qs[0].Comment.count()

    def get_absolute_url(self):
        return reverse('post_detail', kwargs={'pk': self.pk})

    def children(self):
        return Comment.objects.filter(parent=self)

    @property
    def is_parent(self):
        if self.parent is not None:
            return False
        return True

blogApp/forms.py
from django import forms
from blogApp.models import Post,Comment,Category,User
from admin_user.models import Profile




choices = Category.objects.all().values_list('name','name')

choice_list = []

for item in choices:
    choice_list.append(item)

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title','author','category','text','featured_image']

        widgets = {
            'author':forms.TextInput(attrs={'class':'form-control','value':'','id':'author','type':'hidden'}),
            'category':forms.Select(choices= choice_list, attrs={'class':'form-control'}),
            'title':forms.TextInput(attrs={'class':'form-control','placeholder':'Title'}),
            'text':forms.Textarea(attrs={'class':'form-control', 'placeholder':'Message'})
        }

        def __str__(self):
            return f"{self.post.featured_image} profile"

        # def save(self, *args, **kwargs):
        #     super().save(*args, **kwargs)
        #     img = featured_image.open(self.pic.path)
        #     if img.mode in ("RGBA", "P"): img = img.convert("RGB")
        #     if img.height > 300 or img.width > 300:
        #         output_size = (300, 300)
        #         img.thumbnail(output_size)
        #         img.save(self.pic.path)

choose = User.objects.all()
choose_list = []

for something in choose:
    choose_list.append(something)

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['name','body']
        
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control','value':'','id':'name','type':'hidden'}),
            'body':forms.Textarea(attrs={'class':'form-control', 'placeholder':'Comment'})
        }

blogApp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import( View,TemplateView,CreateView,ListView,
                                  DetailView,UpdateView,DeleteView)
from .models import Post,Comment,Category
from .forms import PostForm,CommentForm
from django.utils import timezone
from django.urls import reverse_lazy,reverse
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponseRedirect
from django.db.models import Count

from django.views.generic.detail import ContextMixin



#Create your views here.

class HomeListView(ListView):
    model = Post
    template_name = 'blogApp/blog.html'
    
    paginate_by = 6
    
    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
        

    def get_context_data(self,*args,**kwargs):
        categories = Post.objects.values('category').annotate(posts_count=Count('category'))
        # print(categories)
        likes = Post.objects.values('likes').annotate(count_like=Count('likes'))
        print(likes)
        display_menu =Category.objects.all()
        recent_post = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')[0:5]
        context = super(HomeListView, self).get_context_data(**kwargs)  
        context ['categories'] = categories
        context ['recent_post'] = recent_post
        context ['display_menu'] = display_menu
        context ['likes'] = likes
        return context


def CategoryListView(request,cats):
    display_menu = Category.objects.all()
    category_post = Post.objects.filter(category=cats.replace('_', ' '))
    active = Post.objects.filter(category=cats.replace('_', ' '))
    context = {}
    context ['cats'] = cats.title().replace('_', ' ')
    context ['category_post'] = category_post
    context ['display_menu'] = display_menu
    context ['active'] = active
    # context ['active'] = current
    return render(request, 'blogApp/post_category.html', context)



def cat_on_all_pages(request):
    return {'display_menu': Category.objects.all()}

class AboutTemplate(TemplateView):
    template_name = 'blogApp/about.html'



class ContactTemplate(TemplateView):
    template_name = 'blogApp/contact.html'



class CreateTemplate(CreateView):
    login_url = 'login'
    redirect_field_name = 'blogApp/blog.html'
    form_class = PostForm
    model = Post
    template_name = 'blogApp/create.html'




class AddCategoryView(CreateView):
    model = Category
    template_name = "blogApp/category.html"
    success_url = reverse_lazy('blog')
    fields = '__all__'



class DraftListView(LoginRequiredMixin,ListView):
    login_url = 'login'
    context_object_name = 'drafts' 
    model = Post 
    template_name = 'blogApp/draft_view.html'
    
    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('-created_date')

def puplish_drafts_post(request,pk):
    post = get_object_or_404(Post,pk=pk)
    post.published_post()
    return redirect('blog')   

class UpdateRecs(LoginRequiredMixin,UpdateView):
    template_name = 'blogApp/update.html'
    fields = ('title','text','category')
    model = Post


class DeletePost(DeleteView):
    template_name = "blogApp/delete.html"
    model = Post
    success_url = reverse_lazy('create')


class PostDetailView(DetailView): 
    template_name = "blogApp/blogdetails.html"
    context_object_name ="post_detail"
    model = Post
    
    
    def form_valid(self, form):
        form.instance.post_id = self.kwargs['pk']
        return super().form_valid(form)
        success_url = reverse_lazy('blog')

    def get_context_data(self,*args,**kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        categories = Post.objects.values('category').annotate(posts_count=Count('category'))
        display_menu = Category.objects.all()
        
        stuff = get_object_or_404(Post, id= self.kwargs['pk'])
        total_likes = stuff.total_likes()

        liked = False
        if stuff.likes.filter(id= self.request.user.id).exists():
            liked = True
        context ['total_likes'] = total_likes
        context ['liked'] = liked
        context ['display_menu'] = display_menu
        context ['categories'] = categories
        return context




def LikeView(request, pk):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    liked = False
    if post.likes.filter(id= request.user.id).exists():
        post.likes.remove(request.user)
        liked = False
    else:
        post.likes.add(request.user)
        liked= True
    return HttpResponseRedirect( reverse('post_detail', args=[str(pk)] ))



class AddCommentView(CreateView):
    model = Comment
    template_name = "blogApp/comment.html"
    form_class = CommentForm
    

    def form_valid(self, form):
        form.instance.post_id = self.kwargs['pk']
        parent_obj = None
        try:
            parent_id = int(form.POST.get('parent_id'))# i replace request with form in this line
        except:
            parent_id = None
        if parent_id:
            parent_qs = Comment.objects.filter(id= parent_id)
            if parent_qs.exists():
                parent_obj = parent_qs.first()
        return super().form_valid(form)
    success_url = reverse_lazy('blog')
    
    def get_context_data(self,*args, **kwargs):
        context = super(AddCommentView, self).get_context_data(**kwargs)
        display_menu = Category.objects.all()
        context ['display_menu'] = display_menu
        return context

class ApproveComment(DetailView):
    model = Comment
    template_name = 'blogApp/approve_comment.html'
    form_class = CommentForm


#############********************PAGINATION CODE AS FUNCTION NOW WORKING WELL ***###########
                                        
                                        
def PostList(request):
    template_name = 'blogApp/blog.html'
    recent_post = Post.objects.filter(published_date__isnull=False).order_by('-published_date')
    object_list = Post.objects.filter(published_date__isnull=False).order_by('-published_date')
    paginator = Paginator(object_list, 8)
    page = request.GET.get('page')
    
    try:
        post_list =paginator.page(page)
    except PageNotAnInteger:
        post_list =paginator.page(1)

        

    except EmptyPage:
        post_list =paginator.page(paginator.num_pages)

    return render(request,template_name,{'page':page,'object_list': object_list, 'recent_post':recent_post})
    

# class BaseContextMixin(ContextMixin):
    
#     def get_context_data(self, **kwargs):
#         context_data = super(BaseContextMixin,self).get_context_data(**kwargs)
#         common_data_first = Category.objects.all()
#         context ['common_data_first'] = common_data_first
#         return context_data

blogApp/templates/blogApp/approve_comment.html
<!DOCTYPE html>
{% extends 'blogApp/base.html' %}
{% load static %}
{% block main_content %}

<!-- Mirrored from azim.commonsupport.com/Belfast/cart.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 28 Jan 2021 14:33:12 GMT -->



    <!-- .preloader -->
    <div class="preloader"></div>
    <!-- /.preloader -->


    <!-- menu-area -->

    <!-- end menu-area -->


    <!-- Hidden Bar -->
    <!-- / Hidden Bar end -->


    <!--Page Title-->
    <section class="page-title centred">
        <div class="container">
            <h3 class="text">Cart</h3>
        </div>
    </section>
    <!--End Page Title-->


    <!-- single shop -->
    <section class="shop-cart">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12 column">
                    <div class="table-outer"> 
                        <table class="cart-table"> 
                            <thead class="cart-header">
                                <tr>
                                    <th class="prod-column">#</th>
                                    <th>&nbsp;</th>
                                    <th>Comment</th>
                                    <th>Action</th>
                                    
                                </tr>
                            </thead> 
                            {% for items in comment_list %}              
                            <tbody>
                                <tr class="item">
                                    <td colspan="2" class="image-box">
                                        <div class="column-box">
                                            
                                            <div class="text">{{items.name}}</div>
                                        </div>
                                    </td>
                                    <td class="sub-total">{{ items.body}}</td>
                                    <td class="qty">
                                        <div class="addto-cart-box">
                                            <a href="#"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                                        </div>
                                    </td>
                                    <td class="total">$45</td>
                                    <td class="remove"></td>
                                </tr>
                                <!-- <tr class="item">
                                    <td colspan="2" class="image-box">
                                        <div class="column-box">
                                            <figure class="prod-thumb"><a href="#"><img src="images/shop/2.png" alt=""></a></figure>
                                            <div class="text">Casual Top Wear</div>
                                        </div>
                                    </td>
                                    <td class="sub-total">$50</td>
                                    <td class="qty">
                                        <div class="addto-cart-box">
                                            <input class="quantity-spinner" type="text" value="1" name="quantity">
                                        </div>
                                    </td>
                                    <td class="total">$50</td>
                                    <td class="remove"><a href="#"><i class="fa fa-trash-o" aria-hidden="true"></i></a></td>
                                </tr>                       -->
                            </tbody>
                            {% endfor %}
                        </table>
                    </div> 
                </div>
            </div>
            <div class="cart-box">
                <div class="cart-one"><a href="#">CONTINUE SHOPPING</a></div>
                <div class="cart-two"><button type="button">UPDATE SHOPPING CART</button></div>
            </div>
            <div class="row">
                <div class="col-md-3 col-sm-6 col-xs-12 cart-column">
                    <div class="coupon-code cart-box">
                        <h5>Coupon Code</h5>
                        <div class="text">Enter your coupon code if you have one..</div>
                        <div class="form-group">
                            <input type="text" placeholder="Your code">
                            <button type="submit">APPLY COUPON CODE</button>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12 col-md-offset-5 cart-column">
                    <div class="cart-total">
                        <h5>Cart Total</h5>
                        <div class="text">Sub-Total<span>$95</span></div>
                        <div class="text">GRAND Total<span>$95</span></div>
                        <div class="button"><a href="#" class="btn-one">PROCEED TO CHECKOUT</a></div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- single shop end -->


    <!-- instagram-section -->
    <section class="instagram-section centred">
        <div class="container">
            <div class="instagram-title">FOLLOW @ INSTAGRAM</div>
            <ul class="instagram-img-list clearfix">
                <li><a href="#"><figure><img src="images/home/f1.jpg" alt=""></figure></a></li>
                <li><a href="#"><figure><img src="images/home/f2.jpg" alt=""></figure></a></li>
                <li><a href="#"><figure><img src="images/home/f3.jpg" alt=""></figure></a></li>
                <li><a href="#"><figure><img src="images/home/f4.jpg" alt=""></figure></a></li>
                <li><a href="#"><figure><img src="images/home/f5.jpg" alt=""></figure></a></li>
            </ul>
        </div>
    </section>
    <!-- instagram-section -->

    
    <!-- main footer -->
   
    <!-- main footer end -->


    <!-- footer bottom -->
    <section class="footer-bottom footer-bottom-one centred">
        <div class="container">
            <div class="copyright">CopyrightS © 2018 <a href="#">BELFAST</a>. All rights reserved</div>
        </div>
    </section>
    <!-- footer bottom -->


{% endblock %}
<!-- Mirrored from azim.commonsupport.com/Belfast/cart.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 28 Jan 2021 14:33:14 GMT -->
</html>

blogApp/templates/blogApp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

    <head>
        <!-- Basic Page Needs
        ================================================== -->
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />

        <style>
            .profile-image img {
                position: relative;
                width: 70px;
                height: 70px;
                border-radius: 100%;
            }
        </style>
    
        <!-- Specific Meta
        ================================================== -->
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <meta name="description" content="Blog And Magazine HTML5 Template" />
        <meta name="keywords"
            content="HTML5, Template, Design, blog, blogger, clean, flat, food, html, magazine, modern, news, personal, photographer, template, white  " />
    
        <!-- Titles
        ================================================== -->
        <title>Jimmy | Personal Blog</title>
    
        <!-- Favicons
        ================================================== -->
        <link rel="shortcut icon" href="{% static 'blogApp/assets/images/favicon.ico' %}" />
        <link rel="apple-touch-icon" sizes="72x72" href="{% static 'blogApp/assets/images/android-icon-72x72.html' %}" />
        <link rel="apple-touch-icon" sizes="114x114" href="{% static 'blogApp/assets/images/apple-icon-144x144.png' %}" />
    
        <!-- Custom Font
        ================================================== -->
        <link
            href="https://fonts.googleapis.com/css2?family=Barlow+Semi+Condensed:wght@400;500;600;700;800&amp;family=Barlow:wght@400;500;600;700&amp;family=Roboto+Slab:wght@400;500;600;700;800&amp;family=Roboto:wght@400;500;700&amp;display=swap"
            rel="stylesheet">
    
        <!-- CSS
        ================================================== -->
        <link rel="stylesheet" href="{% static 'blogApp/assets/css/bootstrap.min.css' %}" />
        <link rel="stylesheet" href="{% static 'blogApp/assets/css/magnific-popup.css' %}" />
        <link rel="stylesheet" href="{% static 'blogApp/assets/css/owl.carousel.min.css' %}" />
        <link rel="stylesheet" href="{% static 'blogApp/assets/css/simple-scrollbar.css' %}" />
        <link rel="stylesheet" href="{% static 'blogApp/assets/css/fontawesome.all.min.css' %}" />
        <link rel="stylesheet" href="{% static 'blogApp/assets/css/style.css' %}" />
        <link rel="stylesheet" href="{% static 'blogApp/assets/css/color/color-one.css' %}" />
    
        <script src="{% static 'blogApp/assets/js/modernizr.min.js' %}"></script>
    </head>

<body class="boxed_wrapper">

    {% include 'blogApp/navbar/header.html' %}

    {% block main_content %}

    {% endblock %}



    {% include 'blogApp/navbar/footer.html' %}

</body>



	<!-- All The JS Files
		================================================== -->
        <script src="{% static 'blogApp/assets/js/jquery.js' %}"></script>
        <script src="{% static 'blogApp/assets/js/popper.min.js' %}"></script>
        <script src="{% static 'blogApp/assets/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'blogApp/assets/js/plugins.js' %}"></script>
        <script src="{% static 'blogApp/assets/js/imagesloaded.pkgd.min.js' %}"></script>
        <script src="{% static 'blogApp/assets/js/simple-scrollbar.min.js' %}"></script>
        <script src="{% static 'blogApp/assets/js/jquery.magnific-popup.min.js' %}"></script>
        <script src="{% static 'blogApp/assets/js/masonry.pkgd.min.js' %}"></script>
        <script src="{% static 'blogApp/assets/js/theia-sticky-sidebar.min.js' %}"></script>
        <script src="{% static 'blogApp/assets/js/ResizeSensor.min.js' %}"></script>
        <script src="{% static 'blogApp/assets/js/owl.carousel.min.js' %}"></script>
        <script src="{% static 'blogApp/assets/js/scrolla.jquery.min.js' %}"></script>
        <script src="{% static 'blogApp/assets/js/main.js' %}"></script>
        <!-- main-js -->

blogApp/templates/blogApp/comment.html
{% extends 'blogApp/base.html' %}
{% load static %}
{% block main_content %}

<div class="rn-page-title">
    <div class="rn-pt-overlayer"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="rn-page-title-inner">
                    <h1>Comment</h1>
                </div>
            </div>
        </div>
    </div>
    </div>
    <!-- End Page Title-->
    
    <!-- Page Content-->
    <section class="rn-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <!-- Contact Form-->
                <h2 class="rn-simple-title">Comment</h2>
                <div class="rn-contact-form">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <br>
                        <input type="submit" class="btn btn-primary" value="Add Comment">
                    </form>
                </div>
                <!-- End Contact Form-->
            </div>
        </div>
    </div>
    </section>
    <script>
        var name = '{{user.id}}';
        document.getElementById('name').value = name;
    </script>
{% endblock %}

blogApp/templates/blogApp/create.html
{% extends 'blogApp/base.html' %}
{% load static %}
{% block main_content %}

<div class="rn-page-title">
    <div class="rn-pt-overlayer"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="rn-page-title-inner">
                    <h1>Create Post</h1>
                </div>
            </div>
        </div>
    </div>
    </div>
    <!-- End Page Title-->
    
    <!-- Page Content-->
    <section class="rn-section">
        {% if user.is_authenticated %}
       
       
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <!-- Contact Form-->
                <h2 class="rn-simple-title">Create Post</h2>
                <div class="rn-contact-form">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.media }}
                        {{ form.as_p }}
                        <br>
                        <input type="submit" class="btn btn-primary" value="Create Post">
                    </form>
                </div>
                <!-- End Contact Form-->
            </div>
        </div>
         {% else %}
        <div style="font-size: medium; text-align: center;background-color: red;">
            <h3 style="color: silver;">You are not allowed here... and you know it :)</h3>
            </div>
           
        {% endif %}

        <script>
            var author = '{{user.id}}';
            document.getElementById('author').value = author;
        </script>
    </div>

    
    </section>

{% endblock %}

blogApp/templates/blogApp/post_list33.html
{% extends 'blogApp/base.html' %}
{% load static %}
{% block main_content %}

<!-- <div class="container">
    <nav class="row">
        {% if post_list.has_other_pages %}
        <nav aria-label="Page navigation container"></nav>
        <ul class="pagination justify-content-center">
            {% if post_list.has_previous %}
            <li><a href="?page={{ post_list.previous_page_number " class="page-link">Previous</a></li>
            {% endif %}
            {% if post_list.has_next %}

            <li><a href="?page={{ post_list.next_page_number " class="page-link">Next</a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div> -->
{% endblock %}